### PR TITLE
Congratulations with 0.6.0

### PR DESCRIPTION
**Pull request by alex-slynko**

### CODE REVIEW

**Comment by akshaymankar** [comment]
Thanks Alex! :smile:

**Comment by alex-slynko** [comment]
@akshaymankar when should we get next dhall-fly?
I can't build the one from master and it seems I can't use new dhall-concourse without it.

**Comment by akshaymankar** [comment]
Oh no, I forgot about it. I will publish the release for dhall-fly this weekend. 
Until then you can use `dhall-to-json` and `jq`, they are much faster and have ability to give nicer errors.

**Comment by akshaymankar** [comment]
@alex-slynko, you can brew upgrade now :)

**Comment by alex-slynko** [comment]
I've sent this PR so we can properly run `brew upgrade`
https://github.com/Homebrew/homebrew-core/pull/50634

**Pull request merged**
